version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    image: new_self_management_api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - DB_HOST=db
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: api_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: mysql:8
    container_name: api_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: api_redis
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: api_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: api_swagger
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api-docs/swagger.json
    volumes:
      - ./swagger:/api-docs

volumes:
  db_data:
